/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const InvoiceDocument = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'created' : Time,
  'jsonData' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteDocument' : IDL.Func([IDL.Nat], [], []),
  'getDocument' : IDL.Func([IDL.Nat], [InvoiceDocument], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(InvoiceDocument)], ['query']),
  'saveDocument' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const InvoiceDocument = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'created' : Time,
    'jsonData' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteDocument' : IDL.Func([IDL.Nat], [], []),
    'getDocument' : IDL.Func([IDL.Nat], [InvoiceDocument], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(InvoiceDocument)], ['query']),
    'saveDocument' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };